version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - 9411:9411
    networks:
      - my-network

  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
    command: ["redis-server", "--requirepass", "systempass"]
    ports:
      - 6379:6379
      - 8001:8001 # 레디스 인사이트 접속 포트
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "systempass", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis_exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    depends_on:
      - redis-stack
    networks:
      - my-network
    environment:
      REDIS_PASSWORD: "systempass"
      REDIS_ADDR: "redis-stack:6379"

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'banking'
      POSTGRES_PASSWORD: 'banking20'
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U banking -d auth" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - my-network

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "user=banking password=banking20 host=postgres port=5432 dbname=auth sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://43.202.30.15:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: "false"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
  config:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: native # 원하는 프로파일 설정
        MODULE: config
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "19000:19000"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://43.202.30.15:19000/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # 컨테이너 시작 후 60초를 기다린 후 체크 시작
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/config:latest

  eureka:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: eureka.server
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
    ports:
      - "19090:19090"
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/eureka.server:latest

  gateway:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: gateway
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
    ports:
      - "19092:19092"
    depends_on:
      config:
        condition: service_healthy
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/gateway:latest

  auth:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: auth
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
    ports:
      - "19093:19093"
    networks:
      - my-network
    depends_on:
      config:
        condition: service_healthy
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/auth:latest

  personal:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: personal
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/personal:latest

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/product:latest

  account:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: account
    environment:
      SPRING_PROFILES_ACTIVE: prod # 운영 환경 프로파일 설정
      ENCRYPTOR_PASSWORD: ${ENCRYPTOR_PASSWORD}
    ports:
      - "19095:19095"
    depends_on:
      config:
        condition: service_healthy
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/account:latest

  notification:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: notification
    environment:
      SPRING_PROFILES_ACTIVE: prod # 운영 환경 프로파일 설정
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
    ports:
      - "19097:19097"
    depends_on:
      config:
        condition: service_healthy
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/notification:latest

  performance:
    build:
      dockerfile: ./Dockerfile
      args:
        TEST_SPRING_PROFILES_ACTIVE: prod
        MODULE: performance
    environment:
      SPRING_PROFILES_ACTIVE: prod # 운영 환경 프로파일 설정
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
    ports:
      - "19098:19098"
    depends_on:
      config:
        condition: service_healthy
    networks:
      - my-network
    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/performance:latest

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local

networks:
  my-network:
    driver: bridge