version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - 9411:9411
    networks:
      - my-network


  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
    command: ["redis-server", "--requirepass", "systempass"]
    ports:
      - 6379:6379
      - 8001:8001 # 레디스 인사이트 접속 포트
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "systempass", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 3



  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'banking'
      POSTGRES_PASSWORD: 'banking20'
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U banking -d auth" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - my-network


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3181:3181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 3181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - my-network


  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:3181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:3181
      KAFKA_CLUSTERS_0_READONLY: "false"
    networks:
      - my-network




#  config:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: native # 원하는 프로파일 설정
#        MODULE: config
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#    ports:
#      - "19000:19000"
#    networks:
#      - my-network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://config:19000/actuator/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/config
#
#  eureka:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: dev
#        MODULE: eureka.server
#    environment:
#      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
#    ports:
#      - "19090:19090"
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/server
#
#  gateway:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: gateway
#    environment:
#      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
#    ports:
#      - "19092:19092"
#    depends_on:
#      config:
#        condition: service_healthy
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/gateway
#
#  auth:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: auth
#    environment:
#      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
#    ports:
#      - "19093:19093"
#    networks:
#      - my-network
#    depends_on:
#      config:
#        condition: service_healthy
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/auth
#
#  personal:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: personal
#    environment:
#      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
#    ports:
#      - "19096:19096"
#    depends_on:
#      config:
#        condition: service_healthy
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/personal
#
#  product:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: product
#    environment:
#      SPRING_PROFILES_ACTIVE: prod  # 운영 환경 프로파일 설정
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#      AWS_REGION: ${AWS_REGION}
#    ports:
#      - "19094:19094"
#    depends_on:
#      config:
#        condition: service_healthy
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/product
#
#  account:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: account
#    environment:
#      SPRING_PROFILES_ACTIVE: prod # 운영 환경 프로파일 설정
#      ENCRYPTOR_PASSWORD: ${ENCRYPTOR_PASSWORD}
#    ports:
#      - "19095:19095"
#    depends_on:
#      config:
#        condition: service_healthy
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/account
#
#  notification:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: notification
#    environment:
#      SPRING_PROFILES_ACTIVE: prod # 운영 환경 프로파일 설정
#      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
#    ports:
#      - "19097:19097"
#    depends_on:
#      config:
#        condition: service_healthy
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/notification
#
#  performance:
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        TEST_SPRING_PROFILES_ACTIVE: prod
#        MODULE: performance
#    environment:
#      SPRING_PROFILES_ACTIVE: prod # 운영 환경 프로파일 설정
#      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
#    ports:
#      - "19098:19098"
#    depends_on:
#      config:
#        condition: service_healthy
#    networks:
#      - my-network
#    image: 211125657451.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/performance


volumes:
  postgres_data:
    driver: local


networks:
  my-network:
    driver: bridge
