# Auth Server dev config

server:
  port: 19095

spring:
  # main:
  #  web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: AccountService  # 애플리케이션 이름을 'gateway-service'로 설정



eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    health-check:
      enabled: true
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
    lease-renewal-interval-in-seconds: 30  # 기본값은 30초, 서비스 상태 갱신 주기
    lease-expiration-duration-in-seconds: 90  # 기본값은 90초, 서비스 갱신이 없을 때 만료 시간
    health-check-url-path: /actuator/health # 헬스 체크를 통한 정상작동 확인

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

common:
  bean:
    security:
      enabled: true

test:
  config-name: Auth-Server