spring:
  application:
    name: server
  cloud:
    bus:
      destination: banking-platform.dev.event.config-event.json
      refresh:
        enabled: true
      env:
        enabled: true


eureka:
  client:
    register-with-eureka: false # Eureka 서버 자체는 다른 Eureka 서버에 등록되지 않음
    fetch-registry: false # Eureka 서버는 레지스트리를 스스로 조회할 필요 없음
    service-url:
      defaultZone: http://eureka:19090/eureka/
  server:
    enable-self-preservation: true # Self-preservation 모드 활성화 (네트워크 이슈로 인해 과도한 서비스 인스턴스 제거 방지)
    eviction-interval-timer-in-ms: 60000  # 인스턴스 제거 주기(기본값은 60초)


server:
  port: 19090

management:
  endpoints:
    web:
      exposure:
        include: "*, busrefresh"
  endpoint:
    health:
      show-details: always
    env:
      show-values: "ALWAYS"
test:
  config-name: Server3